service: lp-back

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true
  excludeDevDependencies: true

functions:
  main:
    handler: src/lambda.handler
    timeout: 29
    events:
      - http:
          method: any
          path: /{any+}
